### ISSUE TITLE
mouse event doesn't make css work

### ISSUE THREAD

**Issue by aisensiy** [n1k0/casperjs#208]
Casperjs can just trigger events write by javascript, but not with css. 

```css
.container .prev {
  display: none;
}

.container:hover .prev {
  display: block;
}
```

With the example above, when i try

```javascript
casper.mouseEvent('mouseover', '.container');
```
The `.prev` elment doesn't show up.
